In [17]:
import pandas as pd
import numpy as np

In [18]:
netflix=pd.read_csv("NFLX.csv")
netflix

Date        Open        High         Low       Close   Adj Close  \
0     2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
1     2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2     2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   
3     2018-02-08  267.079987  267.619995  250.000000  250.100006  250.100006   
4     2018-02-09  253.850006  255.800003  236.110001  249.470001  249.470001   
...          ...         ...         ...         ...         ...         ...   
1004  2022-01-31  401.970001  427.700012  398.200012  427.140015  427.140015   
1005  2022-02-01  432.959991  458.480011  425.540009  457.130005  457.130005   
1006  2022-02-02  448.250000  451.980011  426.480011  429.480011  429.480011   
1007  2022-02-03  421.440002  429.260010  404.279999  405.600006  405.600006   
1008  2022-02-04  407.309998  412.769989  396.640015  410.170013  410.170013   

        Volume  
0     11896100  
1     12595800  
2      8981500  
3      9306700  
4     16906900  
...        ...  
1004  20047500  
1005  22542300  
1006  14346000  
1007   9905200  
1008   7782400  

[1009 rows x 7 columns]

In [19]:
netflix.isna().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [20]:
del netflix["Date"]
del netflix["Adj Close"]

In [21]:
print(netflix.shape)
netflix

(1009, 5)


Open        High         Low       Close    Volume
0     262.000000  267.899994  250.029999  254.259995  11896100
1     247.699997  266.700012  245.000000  265.720001  12595800
2     266.579987  272.450012  264.329987  264.559998   8981500
3     267.079987  267.619995  250.000000  250.100006   9306700
4     253.850006  255.800003  236.110001  249.470001  16906900
...          ...         ...         ...         ...       ...
1004  401.970001  427.700012  398.200012  427.140015  20047500
1005  432.959991  458.480011  425.540009  457.130005  22542300
1006  448.250000  451.980011  426.480011  429.480011  14346000
1007  421.440002  429.260010  404.279999  405.600006   9905200
1008  407.309998  412.769989  396.640015  410.170013   7782400

[1009 rows x 5 columns]

In [22]:
Y=np.array(netflix.Close)
Y.shape
Y

array([254.259995, 265.720001, 264.559998, ..., 429.480011, 405.600006,
       410.170013])

In [23]:
del netflix["Close"]
netflix

Open        High         Low    Volume
0     262.000000  267.899994  250.029999  11896100
1     247.699997  266.700012  245.000000  12595800
2     266.579987  272.450012  264.329987   8981500
3     267.079987  267.619995  250.000000   9306700
4     253.850006  255.800003  236.110001  16906900
...          ...         ...         ...       ...
1004  401.970001  427.700012  398.200012  20047500
1005  432.959991  458.480011  425.540009  22542300
1006  448.250000  451.980011  426.480011  14346000
1007  421.440002  429.260010  404.279999   9905200
1008  407.309998  412.769989  396.640015   7782400

[1009 rows x 4 columns]

In [24]:
X=netflix.values
X

array([[2.62000000e+02, 2.67899994e+02, 2.50029999e+02, 1.18961000e+07],
       [2.47699997e+02, 2.66700012e+02, 2.45000000e+02, 1.25958000e+07],
       [2.66579987e+02, 2.72450012e+02, 2.64329987e+02, 8.98150000e+06],
       ...,
       [4.48250000e+02, 4.51980011e+02, 4.26480011e+02, 1.43460000e+07],
       [4.21440002e+02, 4.29260010e+02, 4.04279999e+02, 9.90520000e+06],
       [4.07309998e+02, 4.12769989e+02, 3.96640015e+02, 7.78240000e+06]])

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [26]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=0)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((756, 4), (253, 4), (756,), (253,))

In [27]:
clf=LinearRegression()
clf.fit(x_train,y_train)
y_predict=clf.predict(x_test)

In [28]:
print(clf.coef_,clf.intercept_)
# y= m1x1 + m2x2 + m3x3 + m4x4 + c

[-5.98637670e-01  7.42752459e-01  8.57948723e-01  9.68159263e-08] -0.707759558722671


In [29]:
clf.score(x_test,y_test)

0.9982601041694817

In [30]:
open_=float(input("Enter opening Price :"))
high_=float(input("Enter highest Price :"))
low_=float(input("Enter lowest Price :"))
volume_=int(input("Enter total volume :"))
test_=np.array([[open_,high_,low_,volume_]])
pred=clf.predict(test_)
print("The approx closing price is : ",pred[0])
# 262.0 267.89 250.02 11896100

Enter opening Price :262
Enter highest Price :267.89
Enter lowest Price :250.02
Enter total volume :11896100
The approx closing price is :  257.0811989277219
